Traceback (most recent call last):
  File "main.py", line 458, in <module>
    run(
  File "main.py", line 256, in run
    assert len(models) > 0
AssertionError
